app:
  fullName: user-be-prod
  name: user
  type: be
  env: prod

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: v1.1.3

ingress:
  host: api.xquare.app
  prefix: /users
