app:
  fullName: dms-be-prod
  name: dms
  type: be
  env: prod

container:
  port: 8080
  image:
    registry: registry.hub.docker.com
    version: fef20b51f74c657db9cc91c95a888f1916a3b721

ingress:
  prefix: /dms

host: server.xquare.app
