apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xquare
  namespace: argocd

spec:
  project: xquare

  source:
    repoURL: https://github.com/team-xquare/xquare-manifest-repository.git
    targetRevision: HEAD
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: xquare

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
