apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xquare-prod
  namespace: argocd

spec:
  project: xquare-prod

  source:
    repoURL: https://github.com/team-xquare/xquare-gitops-repo-production.git
    targetRevision: HEAD
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: xquare-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
