app:
  fullName: contour-middleware-be-prod
  name: contour-middleware
  type: be
  env: prod

container:
  port: 9443
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: v0.0.10
