app:
  fullName: application-be-prod
  name: application
  type: be
  env: prod

container:
  port: 8080
  image:
    registry: 718436679669.dkr.ecr.ap-northeast-2.amazonaws.com
    version: v0.0.9

ingress:
  host: api.xquare.app
  prefix: /applications
