apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: point-be-prod
  namespace: argocd

spec:
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: be-prod

  project: {{ .Values.spec.project }}

  source:
    path: charts/be/point
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
