apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-backend-production
  namespace: argocd

spec:
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: test2-backend-production

  project: {{ .Values.spec.project }}

  source:
    path: charts/backend/test2
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
