app:
  fullName: apply-fe-prod
  name: apply
  type: fe
  env: prod

container:
  port: 3000
  image:
    registry: registry.hub.docker.com
    version: 0.0.3

ingress:
  prefix: /apply

host: webview.xquare.app
