apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.type }}-{{ .Values.app.env }}
spec:
  dnsNames:
    - {{ .Values.app.name }}
  secretName: contour-middleware-cert
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
