app: 
  fullName: cloud-config-be-prod
  name: cloud-config
  type: be
  env: prod


container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: v0.1.2

ingress:
  host: api.xquare.app
  prefix: /cloud-config
  