apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.app.name}}
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
spec:
  tls:
  - secretName: be-prod-cert
    hosts:
    - api.xquare.app
    
  rules:
  - host: api.xquare.app
    http:
      paths:
      - pathType: Prefix
        path: {{.Values.ingress.prefix}}
        backend:
          service:
            name: {{.Values.app.name}}
            port:
              number: 80
