app: 
  fullName: dormitory-admin-fe-prod
  name: dormitory-admin
  type: fe
  env: prod


container:
  port: 3000
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 1.0.12

ingress:
  host: admin.xquare.app
  prefix: /
  