apiVersion: v2
name: cert-manager-prod
description: A Helm chart for cert-manager

type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: 1.8.0
    repository: https://charts.jetstack.io
