apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: assets-fe-fe-prod
  namespace: argocd

spec:
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: fe-prod

  project: {{ .Values.spec.project }}

  source:
    path: charts/fe/assets-fe
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
