apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app }}-cert
spec:
  dnsNames:
  - {{ .Values.host }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: {{ .Values.app }}-cert