apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app}}-svc
  labels:
    app: {{.Values.app}}-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Values.app}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

